- name:  config inactive_account_time 
  hosts: "{{ HOSTS }}"
  collections:
    - community.general.pbrun
  gather_facts: false

  tasks:
  - name: create the path
    file:
      path: "/tmp/config_inactive_at"
      state:  directory

  - name: copy the local script file to remote servers
    copy:
      src:  config_inactive_accttime.sh 
      dest: "/tmp/config_inactive_at"
      mode: '755'

  - name: copy the local sql file to remote servers
    copy:
      src:  config_inactive_accttime.sql 
      dest: "/tmp/config_inactive_at"


  - name: run config_inactive_accttime.sh 
    shell:
      cmd: /tmp/config_inactive_at/config_inactive_accttime.sh
    ignore_errors: yes

  - shell: (cd /tmp/config_inactive_at; find . -name "*.log"  -o -name "*.spool" -type f) | cut -d'/' -f2
    register: files_to_copy

  - debug:
      var:  files_to_copy

  - fetch: src=/tmp/config_inactive_at/{{ item }} dest=./logs
    with_items: "{{ files_to_copy.stdout_lines }}"


  - name: delete the path
    file:
       path: "/tmp/config_inactive_at"
       state: absent

