- name:  get Oracle GI software home, version and port 
  hosts: "{{ HOSTS }}"
  collections:
    - community.general.pbrun
  gather_facts: false

  tasks:
  - name: create the path
    file:
      path: "/tmp/dbinv_gi" 
      state:  directory

  - name: copy the local script file 1 to remote server
    copy:
      src:  gi_home_ver_get.sh
      dest: "/tmp/dbinv_gi" 
      mode: '755'

  - name: run gi_home_ver_get.sh script 
    shell:
      cmd: /tmp/dbinv_gi/gi_home_ver_get.sh
    ignore_errors: yes
  

  - name: fetch remote dat file
    fetch:
       src:  /tmp/dbinv_gi/gi_swhv_data.csv
       dest: ./swhv/ 

  - name: remove the path
    file:
       path: "/tmp/dbinv_gi" 
       state: absent 

