rem script:  longops.sql
rem  - Display the progress of some operations like table scan 
rem 

SET ECHO OFF
COL HOURS          FORMAT 999,990.99
COL MESSAGE        FORMAT A22
COL OPNAME         FORMAT A16        HEA "OPERATION"
COL PCT_COMPLETE   FORMAT 99.9        HEA "PCT" 
COL SERIAL#        FORMAT 99999
COL SID            FORMAT 9999
COL STARTED        FORMAT A16        HEA "START TIME"
COL TARGET         FORMAT A16
COL TARGET_DESC    FORMAT A16
COL REMAIN_MIN     FORMAT 99,999,999
COL ELASPSED_MIN   FORMAT 99,999,999
COL UNITS          FORMAT A10
COL USERNAME       FORMAT A15
set linesize 120
-- SET ECHO ON
SELECT SID
--      ,SERIAL#
      ,USERNAME
      ,OPNAME
      ,TO_CHAR(START_TIME,'MM/DD HH24:MI:SS') STARTED
      , decode(totalwork, 0, 100,SOFAR/TOTALWORK*100)   PCT_COMPLETE
      ,ELAPSED_SECONDS/60       ELASPSED_MIN
--     ,TOTALWORK
--      ,UNITS
     ,TIME_REMAINING/60         REMAIN_MIN
   FROM V$SESSION_LONGOPS
   WHERE  USERNAME != 'SYS'
--    and SOFAR/TOTALWORK*100 !=100
   and  TIME_REMAINING/60 !=0 
   ORDER BY ELAPSED_SECONDS DESC
;

