
   CREATE USER "DB_ADMIN" IDENTIFIED BY VALUES 'S:C9E12933FE731444D8268D2A8BF6E73EF9284912CE1898F7ED8E9CF627D0;H:863912B0C2E1D39593320BEB2B75F52C;T:D4F0ED13586E86F9C19F777FE9F3E7AB7BB10A1CC9F5A38F2BF1
6BC9C3544CD6B5B3F9600E99E97BE9AE4641484540ECB28F8B2981195DFEC3869D773E5CEC480AEFB783C735DB1377C57E9E2A756D8E;C1B9CD1886E776DC'
      DEFAULT TABLESPACE "HB_DATA"
      TEMPORARY TABLESPACE "TEMP"
      PROFILE "ONSHORE_DBA_OPS_PROFILE";

-- Role

   GRANT "DBA" TO "DB_ADMIN";
   GRANT "SELECT_CATALOG_ROLE" TO "DB_ADMIN";
   GRANT "EXP_FULL_DATABASE" TO "DB_ADMIN";
   GRANT "IMP_FULL_DATABASE" TO "DB_ADMIN";

-- Sys priv

  GRANT CREATE ANY CREDENTIAL TO "DB_ADMIN";
  GRANT CREATE EXTERNAL JOB TO "DB_ADMIN";
  GRANT CREATE ANY JOB TO "DB_ADMIN";
  GRANT SELECT ANY DICTIONARY TO "DB_ADMIN";
  GRANT EXECUTE ANY LIBRARY TO "DB_ADMIN";
  GRANT CREATE PROCEDURE TO "DB_ADMIN";
  GRANT CREATE SEQUENCE TO "DB_ADMIN";
  GRANT SELECT ANY TABLE TO "DB_ADMIN";
  GRANT DROP ANY TABLE TO "DB_ADMIN";
  GRANT ALTER ANY TABLE TO "DB_ADMIN";
  GRANT CREATE TABLE TO "DB_ADMIN";
  GRANT BECOME USER TO "DB_ADMIN";
  GRANT UNLIMITED TABLESPACE TO "DB_ADMIN";
  GRANT CREATE SESSION TO "DB_ADMIN";
  GRANT ALTER SYSTEM TO "DB_ADMIN";

-- Object priv

  GRANT EXECUTE ON DIRECTORY "TMPDIR" TO "DB_ADMIN" WITH GRANT OPTION;
  GRANT READ ON DIRECTORY "TMPDIR" TO "DB_ADMIN" WITH GRANT OPTION;
  GRANT WRITE ON DIRECTORY "TMPDIR" TO "DB_ADMIN" WITH GRANT OPTION;
  GRANT EXECUTE ON DIRECTORY "CAW_EXTR" TO "DB_ADMIN" WITH GRANT OPTION;
  GRANT READ ON DIRECTORY "CAW_EXTR" TO "DB_ADMIN" WITH GRANT OPTION;
  GRANT WRITE ON DIRECTORY "CAW_EXTR" TO "DB_ADMIN" WITH GRANT OPTION;
  GRANT WRITE ON DIRECTORY "DATA_PUMP_DIR" TO "DB_ADMIN";
  GRANT READ ON DIRECTORY "DATA_PUMP_DIR" TO "DB_ADMIN";
  GRANT EXECUTE ON DIRECTORY "GGSERR_DIR" TO "DB_ADMIN" WITH GRANT OPTION;
  GRANT READ ON DIRECTORY "GGSERR_DIR" TO "DB_ADMIN" WITH GRANT OPTION;
  GRANT WRITE ON DIRECTORY "GGSERR_DIR" TO "DB_ADMIN" WITH GRANT OPTION;
  GRANT EXECUTE ON DIRECTORY "ALERT_DIR" TO "DB_ADMIN" WITH GRANT OPTION;
  GRANT READ ON DIRECTORY "ALERT_DIR" TO "DB_ADMIN" WITH GRANT OPTION;
  GRANT WRITE ON DIRECTORY "ALERT_DIR" TO "DB_ADMIN" WITH GRANT OPTION;
  GRANT EXECUTE ON "SYS"."DBMS_SWRF_INTERNAL" TO "DB_ADMIN";
  GRANT EXECUTE ON "SYS"."DBMS_WORKLOAD_REPOSITORY" TO "DB_ADMIN";
  GRANT SELECT ON "SYS"."GV_$ACTIVE_SESSION_HISTORY" TO "DB_ADMIN";
  GRANT EXECUTE ON "SYS"."DBMS_SHARED_POOL" TO "DB_ADMIN";
  GRANT EXECUTE ON "SYS"."DBMS_BACKUP_RESTORE" TO "DB_ADMIN";
  GRANT EXECUTE ON "SYS"."UTL_FILE" TO "DB_ADMIN";
  GRANT SELECT ON "SYS"."DBA_TAB_COLUMNS" TO "DB_ADMIN";
  GRANT SELECT ON "SYS"."GV_$INSTANCE" TO "DB_ADMIN";
  GRANT SELECT ON "SYS"."V_$SESSION" TO "DB_ADMIN";
  GRANT UPDATE ON "BNDL"."BL_USOC_ORDER_QUEUE" TO "DB_ADMIN";
  GRANT INSERT ON "OPS$ORACLE"."PLAN_TABLE" TO "DB_ADMIN";

-- tablespace quota

  DECLARE
  TEMP_COUNT NUMBER;
  SQLSTR VARCHAR2(200);
BEGIN
  SQLSTR := 'ALTER USER "DB_ADMIN" QUOTA UNLIMITED ON "USERS"';
  EXECUTE IMMEDIATE SQLSTR;
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE = -30041 THEN
      SQLSTR := 'SELECT COUNT(*) FROM USER_TABLESPACES
              WHERE TABLESPACE_NAME = ''USERS'' AND CONTENTS = ''TEMPORARY''';
      EXECUTE IMMEDIATE SQLSTR INTO TEMP_COUNT;
      IF TEMP_COUNT = 1 THEN RETURN;
      ELSE RAISE;
      END IF;
    ELSE
      RAISE;
    END IF;
END;
/

